### ISSUE TITLE
Object Initializers with collection read-only property initialization fail to be compiled in map capable to start

### ISSUE THREAD

**Issue by DrizztDoUrden** [Drake53/CSharp.lua#3]
WC3 version 1.33.

My package refs for the map building project:
```MSBuild
    <PackageReference Include="War3Net.Build" Version="5.5.5" />
    <PackageReference Include="War3Net.CSharpLua.CoreSystem" Version="1.7.18" />
```
For the map entry point project:
```MSBuild
    <PackageReference Include="War3Api.Blizzard" Version="1.33.0" />
    <PackageReference Include="War3Api.Common" Version="1.33.0" />
    <PackageReference Include="WCSharp.Events" Version="2.0.9" />
```
Although not very useful to fix per se, this produces NullReferenceException in the compiler:
```C#
    internal class TestClass
    {
        public List<int> Items { get; } = new();
    }
    internal static class Program
    {
        private static void Main()
        {
            var test = new TestClass
            {
                Items = { },
            };
        }
    }
```
<details>
<summary>Transpiler error log</summary>
1>Unhandled exception. CSharpLua.BugErrorException: SourceLocation(C:/Code/JASAOS_CS/src/JASAOS.Game\Program.cs@24:13)"var test = new TestClass
1>            {
1>                Items =
1>                {
1>                },
1>            };": Compiler has a bug, thanks to commit issue at https://github.com/yanghuan/CSharp.lua/issue
1> ---> System.NullReferenceException: Object reference not set to an instance of an object.
1>   at CSharpLua.LuaSyntaxGenerator.GetTypeName(ISymbol symbol, LuaSyntaxNodeTransform transform)
1>   at CSharpLua.LuaSyntaxNodeTransform.GetTypeName(ISymbol symbol)
1>   at CSharpLua.LuaSyntaxNodeTransform.BuildArrayTypeFromInitializer(IArrayTypeSymbol arrayType, InitializerExpressionSyntax initializer)
1>   at CSharpLua.LuaSyntaxNodeTransform.VisitInitializerExpression(InitializerExpressionSyntax node)
1>   at Microsoft.CodeAnalysis.CSharp.Syntax.InitializerExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
1>   at CSharpLua.Utility.Accept[T](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform)
1>   at CSharpLua.Utility.AcceptExpression(CSharpSyntaxNode node, LuaSyntaxNodeTransform transform)
1>   at CSharpLua.LuaSyntaxNodeTransform.FillObjectInitializerExpression(LuaIdentifierNameSyntax temp, InitializerExpressionSyntax node)
1>   at CSharpLua.LuaSyntaxNodeTransform.GetObjectCreationInitializer(LuaExpressionSyntax creationExpression, InitializerExpressionSyntax initializer, ExpressionSyntax node)
1>   at CSharpLua.LuaSyntaxNodeTransform.GetObjectCreationInitializer(LuaExpressionSyntax creationExpression, BaseObjectCreationExpressionSyntax node)
1>   at CSharpLua.LuaSyntaxNodeTransform.VisitObjectCreationExpression(ObjectCreationExpressionSyntax node)
1>   at Microsoft.CodeAnalysis.CSharp.Syntax.ObjectCreationExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
1>   at CSharpLua.Utility.Accept[T](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform)
1>   at CSharpLua.Utility.AcceptExpression(CSharpSyntaxNode node, LuaSyntaxNodeTransform transform)
1>   at CSharpLua.LuaSyntaxNodeTransform.VisitExpression(ExpressionSyntax node)
1>   at CSharpLua.LuaSyntaxNodeTransform.VisitEqualsValueClause(EqualsValueClauseSyntax node)
1>   at Microsoft.CodeAnalysis.CSharp.Syntax.EqualsValueClauseSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
1>   at CSharpLua.Utility.Accept[T](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform)
1>   at CSharpLua.LuaSyntaxNodeTransform.VisitVariableDeclarator(VariableDeclaratorSyntax node)
1>   at Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclaratorSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
1>   at CSharpLua.Utility.Accept[T](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform)
1>   at CSharpLua.LuaSyntaxNodeTransform.VisitVariableDeclaration(VariableDeclarationSyntax node)
1>   at Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
1>   at CSharpLua.Utility.Accept[T](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform)
1>   at CSharpLua.LuaSyntaxNodeTransform.VisitLocalDeclarationStatement(LocalDeclarationStatementSyntax node)
1>   at Microsoft.CodeAnalysis.CSharp.Syntax.LocalDeclarationStatementSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
1>   at CSharpLua.LuaSyntaxNodeTransform.BlockCommonNode.Visit(LuaSyntaxNodeTransform transfor)
1>   --- End of inner exception stack trace ---
1>   at CSharpLua.LuaSyntaxGenerator.Create(Boolean isSingleFile)
1>   at CSharpLua.LuaSyntaxGenerator.GenerateSingleFile(StreamWriter streamWriter, IEnumerable`1 luaSystemLibs, Boolean manifestAsFunction)
1>   at CSharpLua.LuaSyntaxGenerator.GenerateSingleFile(Stream target, IEnumerable`1 luaSystemLibs, Boolean manifestAsFunction)
1>   at CSharpLua.Compiler.CompileSingleFile(Stream target, IEnumerable`1 luaSystemLibs)
1>   at War3Net.Build.Extensions.MapExtensions.CompileScript(Map map, Compiler compiler, MapScriptBuilder mapScriptBuilder, IEnumerable`1 luaSystemLibs, String commonJPath, String blizzardJPath)
1>   at War3Net.Build.Extensions.MapExtensions.CompileScript(Map map, Compiler compiler, IEnumerable`1 luaSystemLibs, String commonJPath, String blizzardJPath)
1>   at War3Net.Build.Extensions.MapExtensions.CompileScript(Map map, Compiler compiler, IEnumerable`1 luaSystemLibs)
1>   at JASAOS.Launcher.Program.Build(BuildArgs args) in C:\Code\JASAOS_CS\src\JASAOS.Launcher\Program.cs:line 70
1>   at JASAOS.Launcher.Program.<>c.<Main>b__3_0(BuildArgs ba) in C:\Code\JASAOS_CS\src\JASAOS.Launcher\Program.cs:line 127
1>   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 notParsedFunc)
1>   at JASAOS.Launcher.Program.Main(String[] args) in C:\Code\JASAOS_CS\src\JASAOS.Launcher\Program.cs:line 125
1>Total time building: 15,4357047 seconds.
</details>

But if you add some values like `1` there would be more practical error, running wc3 with the map just opens the main menu instead of loading the map. This is the lua source produced (omitting unrelated):

```lua
///...
  namespace.class("TestClass", function (namespace)
    local __ctor__
    __ctor__ = function (this)
      this.Items = ListInt32()
    end
    return {
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "Items", 0x6, System.List(System.Int32) }
          },
          class = { 0x4 }
        }
      end
    }
  end)

  namespace.class("Program", function (namespace)
    local Main
    Main = function ()
      local default = JASAOSGame.TestClass()
      local extern = default:Items
      extern:Add(1)
      local test = default
  end)
///...
```

For the sake of laziness, C# source with 1:
```C#
    internal class TestClass
    {
        public List<int> Items { get; } = new();
    }
    internal static class Program
    {
        private static void Main()
        {
            var test = new TestClass
            {
                Items = { 1 },
            };
        }
    }
```

My personal root reason for all of this is that I am making a declarative UI library with sane API and collection initializers make the resulting code actually readable.

**Comment by DrizztDoUrden** [comment]
Workaround for users: allow public setter/init and just initialize with `new() { ... }` instead of `{ ... }`
